### PR TITLE
Style changes to main and talks pages. 

### PR DESCRIPTION
**Pull request by TheRazorace**
Modification of style for the main and talks pages. Inclusion of both events and talks redirects in the main page. Addition of a general talks table in the talks page with general information about the talks. A timezone stamp for all talks has also been added and YouTube links have been updated.

### CODE REVIEW

**Comment by pheyvaer** [comment]
Hi @TheRazorace. Why is the timezone stamp added?

**Comment by TheRazorace** [comment]
Hi! It was a suggestion by Anastasia, for better comprehension of the events' start time. There is an issue about this also, I think.

**Comment by pheyvaer** [comment]
And what is the problem with the current start date which is a timestamp with timezone as well?

**Comment by TheRazorace** [comment]
Anastasia proposed we could add a time zone stamp to make it easier for users to find the events time for their timezone. We are not replacing current start date, we're just adding to it.

**Pull request merged**
