### PR TITLE
Addition of metadata for next talk

### PR DESCRIPTION
**Pull request by TheRazorace**
@pietercolpaert I have added some information for the next talk. Thank you! :)

### CODE REVIEW

**Comment by pheyvaer** [comment]
@TheRazorace You tagged the wrong Pieter 😉  

Can you make sure that previous commits don't get added to this PR?

**Comment by TheRazorace** [comment]
Oh, sorry for that! 😄  
But these previous commits are already merged, right? Why to they still appear as part of this request?

**Comment by pheyvaer** [comment]
That's probably because the branch that you want to merge is not up to date. I would suggest creating a new branch with only the new changes and doing a PR with that one.

**Comment by TheRazorace** [comment]
I don't understand how that is possible, since the last commit in [KNowledgeOnWebScale:main] is the merge with my fork. So my fork should be up to date. I'll try to create another branch

**Pull request closed without merging**
