### PR TITLE
Addition of new COST event (please check for errors because I could not test some things locally, regarding walder post-processing) 

### PR DESCRIPTION
**Pull request by TheRazorace**
Hi! I am Ioannis, Anastasia's PhD student from KU Leuven. I attempted to add another PIDSKG event in the COST action website but I had problems with localhost and the javascript post-processing, so I don't know how some things look! Is it possible you have a look? How can I change the code locally and use node-modules (after I install with yarn) to see what I am implementing in localhost?
Thank you in advance!

### CODE REVIEW

**Comment by pheyvaer** [comment]
Hi @TheRazorace, you can test the website locally via
```shell
npm i 
npm start
```
Open to browser at http://localhost:3000.

**Comment by TheRazorace** [comment]
> Hi @TheRazorace, you can test the website locally via
> 
> ```shell
> npm i 
> npm start
> ```
> 
> Open to browser at http://localhost:3000.

Oh, okay thanks for the feedback! I was trying to do it with walder.

I have added a second event at config.yaml and the respective data at data.ttl . Should I also chande markdown.js for it to work? 

Thank you!

**Comment by pheyvaer** [comment]
`npm start` uses Walder. Are there changes to markdown.js needed? It all depends on what you want to achieve.

**Comment by TheRazorace** [comment]
Yes! I needed to change markdown as well. I tested it and it works fine now! Can you check and merge? Thank you!

**Comment by TheRazorace** [comment]
My problem was I was executing "walder -c" because documentation mentions it, instead of "npm start" and the dependencies couldn't be imported...

**Pull request merged**
